version: 0.2
phases:
  pre_build:
    commands:
      - echo inloggen bij ecr...
      - $(aws ecr get-login --no-include-email --region eu-west-2)
  build:
    commands:
      - echo codebuild Docker image
      - docker build -t faq_chat:latest .
      - docker tag faq_chat:latest 292242131230.dkr.ecr.eu-west-2.amazonaws.com/faq-chat:latest
  post_build:
    commands:
      - echo build Docker image klaar
      - echo push image
      - docker push 292242131230.dkr.ecr.eu-west-2.amazonaws.com/faq-chat:latest
      - printf '[{"name":"faq-chat","imageUri":"292242131230.dkr.ecr.eu-west-2.amazonaws.com/faq-chat"}]' > imagedefinitions.json
artifacts:
  file: imagedefinitions.json