version: '3'
services:
  faq-chat:
    build: .
    ports:
    - "80:3000"
    environment:
      - SLACK_SECRET=${SLACK_SECRET}
      - SLACK_ACCES_TOKEN=${SLACK_ACCES_TOKEN}
  redis:
    image: faq
