version: '3'
services:
  faq1:
    build: .
    ports:
    - "80:3000"
    environment:
      - SLACK_SECRET=${SLACK_SECRET}
      - SLACK_ACCES_TOKEN=${SLACK_ACCES_TOKEN}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - CONFLUENCE_URL=${CONFLUENCE_URL}
      - CONFLUENCE_USER=${CONFLUENCE_USER}
      - CONFLUENCE_PW=${CONFLUENCE_PW}
      - DB_NAME=${DB_NAME}
  redis:
    image: faq
